### ISSUE TITLE
Pull request to original repo?

### ISSUE THREAD

**Issue by iraadit** [rky0930/yolo_v2#1]
Will you do a pull request to the original repo?

Thank you for the amazing work

**Comment by rky0930** [comment]
Thanks. I hope my work has been helpful to you. 
I'd like to PR to original repo. But, there is something i want to improve. ^^;;
I will Pull Request after finishing all my works.  

If you have a question, feel free to contact with me !

**Comment by omg777** [comment]
@rky0930 Hi, Are you completely done this project? 
Thank you for the sharing!

**Comment by rky0930** [comment]
Hi. @omg777 
Although there is no recent update, this project is not done yet. 
I'm try to build Yolo_v3 now. Newer version. better performance... haha.. 
This source code already working well as you see in the matrix. don't worry.
