### ISSUE TITLE
FindFirstFile failed for: /home/ndigm/workspace/git_rky0930/local_run/object_detection/models/coco/yolo/coco_train 

### ISSUE THREAD

**Issue by minda163** [rky0930/yolo_v2#4]
### System information
- **What is the top-level directory of the model you are using**:yolo_v2 
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows10 
- **TensorFlow installed from (source or binary)**:pip
- **TensorFlow version (use command below)**:tensorflow-gpu 1.9
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:9.0 7.4
- **GPU model and memory**:1050 2G
- **Exact command to reproduce**:python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/yolo_v2_darknet_19_mscoco.config

### Describe the problem
when i run this command : python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/yolo_v2_darknet_19_mscoco.config

### Source code / logs

![image](https://user-images.githubusercontent.com/33540791/46536576-79b67e80-c8e1-11e8-8bf5-2749ac036555.png)
 Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/ndigm/workspace/git_rky0930/local_run/object_detection/models/coco/yolo/coco_train/model.ckpt-1533144: Not found: FindFirstFile failed for: /home/ndigm/workspace/git_rky0930/local_run/object_detection/models/coco/yolo/coco_train : 系统找不到指定的路径。
; No such process

**Comment by rky0930** [comment]
Hi. @minda163 
I think you have to download the yolo_v2 weight files and place them into the path you wrote in your config file. 
you can download the files [here](https://drive.google.com/drive/folders/1q23UJgPOVvfmYtP8ufSATaFV54uRdaMI)
Thank you for using my code :D

**Comment by minda163** [comment]
Your reply makes me very happy，thank you！
But I have another issues:

Fist, I clone you repo, and download : YOLOv2_with_darknet19_ckpt
then config as follows:

_`# YOLO with Darknet19 configuration for MSCOCO Dataset.
# Users should configure the fine_tune_checkpoint field in the train config as
# well as the label_map_path and input_path fields in the train_input_reader and
# eval_input_reader. Search for "/home/ndigm/workspace/data/" to find the fields that
# should be configured.

model {
  ssd {
    num_classes: 5
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      yolo_anchor_generator { 
        anchors: [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828]
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 608
        width: 608
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: NONE,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
        }
      }
    }
    feature_extractor {
      type: 'yolo_v2_darknet_19'
      conv_hyperparams {
        activation: NONE,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        confidence_weighted_sigmoid {
          anchorwise_output: true
          object_scale: 5.0,
          noobject_scale: 1.0
        }
      }
      localization_loss {
        weighted_l2 {
          anchorwise_output: true
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 0
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 8 
  optimizer {
    rms_prop_optimizer: {
      learning_rate: {
        manual_step_learning_rate {
          initial_learning_rate: 0.0025
          schedule {
            step: 10000000
            learning_rate: 0.001
          }
          #schedule {
          #  step: 250000
          #  learning_rate: 0.00025 
          #}
          #schedule {
          #  step: 350000
          #  learning_rate: 0.000125
          #}
        }
      }
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint: "D:/yolo_v2/research/object_detection/YOLOv2_with_darknet19_ckpt/inference/model.ckpt"
  from_detection_checkpoint: false
  # Note: The below line limits the training process to 200K steps, which we
  # empirically found to be sufficient enough to train the pets dataset. This
  # effectively bypasses the learning rate schedule (the learning rate will
  # never decay). Remove the below line to train indefinitely.
  #num_steps: 800200
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    ssd_random_crop {
    }
  }
  keep_checkpoint_every_n_hours: 1  
}

train_input_reader: {
  tf_record_input_reader {
    input_path: "D:/yolo_v2/research/object_detection/train.record"
  }
  label_map_path: "D:/yolo_v2/research/object_detection/training/labelmap.pbtxt"
}

eval_config: {
  num_examples: 266
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  max_evals: 1
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "D:/yolo_v2/research/object_detection/test.record"
  }
  label_map_path: "D:/yolo_v2/research/object_detection/training/labelmap.pbtxt"
  shuffle: false
  num_readers: 1
  num_epochs: 1
}
_

`
then I tried to train with my own dataset using YOLOv2.

`python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/yolo_v2_darknet_19_mscoco.config
`
but the following error occurred:

`(base) D:\yolo_v2\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/yolo_v2_darknet_19_mscoco.config
WARNING:tensorflow:From D:\yolo_v2\research\object_detection\trainer.py:210: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
use_batch_norm: True
batch_norm_params: {'decay': 0.9997, 'fused': None, 'updates_collections': 'update_ops', 'epsilon': 0.001, 'is_training': True}
batch_norm_is_training: True
INFO:tensorflow:depth of additional conv before box predictor: 0
WARNING:root:Variable [darknet_19/Conv2D_19/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_19/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_19/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_19/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_20/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_20/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_20/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_20/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_21/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_21/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_21/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_21/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_22/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_22/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_22/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/Conv2D_22/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_1/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_1/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_1/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_1/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_10/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_10/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_10/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_10/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_11/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_11/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_11/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_11/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_12/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_12/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_12/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_12/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_13/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_13/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_13/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_13/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_14/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_14/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_14/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_14/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_15/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_15/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_15/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_15/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_16/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_16/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_16/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_16/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_17/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_17/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_17/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_17/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_18/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_18/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_18/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_18/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_2/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_2/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_2/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_2/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_3/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_3/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_3/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_3/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_4/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_4/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_4/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_4/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_5/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_5/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_5/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_5/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_6/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_6/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_6/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_6/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_7/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_7/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_7/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_7/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_8/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_8/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_8/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_8/weights] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_9/BatchNorm/beta] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_9/BatchNorm/moving_mean] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_9/BatchNorm/moving_variance] not available in checkpoint
WARNING:root:Variable [darknet_19/base/Conv2D_9/weights] not available in checkpoint
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    tf.app.run()
  File "F:\my_install\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 159, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "D:\yolo_v2\research\object_detection\trainer.py", line 255, in train
    init_saver = tf.train.Saver(available_var_map)
  File "F:\my_install\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1338, in __init__
    self.build()
  File "F:\my_install\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "F:\my_install\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1372, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save`

Looking forward to your reply......

**Comment by rky0930** [comment]
Hi @minda163 

Change the option "from_detection_checkpoint" to "True" 
YOLOv2_with_darknet19_ckpt is object detection checkpoint. 
If you just want to use base network checkpoint, keep the from_detection_checkpoint config as False and use this [checkpoint](https://drive.google.com/drive/folders/1bYeZHNyQgTqzYTh_9cW3SoEb75SiH7yQ)

If have more questions, Feel free to tell me!

**Comment by minda163** [comment]
Thank you, I did it. 
Will you keep doing the yolo 3 ?
Can I join in ?

**Comment by rky0930** [comment]
@minda163 Nice!
I'm sorry, i'm not working on Yolo v3 now.. 
I finished the implementation of yolo_v3. and trained the network.. but it had not good enough accuracy and recall at the end,,, and many many tries and ... blah blah 
anyway, I'm not doing the yolo v3 now. I'm so sorry. 
I think there will be more good object detection models in near future. maybe Yolo v4

**Comment by minda163** [comment]
@rky0930 Thank you all the same
