### ISSUE TITLE
Error - "object_detection.protos.AnchorGenerator" has no field named "yolo_anchor_generator".

### ISSUE THREAD

**Issue by mwindowshz** [rky0930/yolo_v2#5]
Hi
Used your git repository
Downloaded, and then run protoc to create .py files in the protos folder as described [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md):
```
# From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.
```

when I try to train using darknet19 I receive an error:

> D:\tf-od-api\yolo_v2-master\research\object_detection>python train.py --logtostderr --train_dir=D:\tf-od-api\3classes\Train_Eval_Base_Dir/Darknet19_ImageNet_ckpt/train --pipeline_config_path=D:\tf-od-api\3classes\Base_Modeles_Dir\Darknet19_ImageNet_ckpt/pipeline.config
> Traceback (most recent call last):
>   File "train.py", line 164, in <module>
>     tf.app.run()
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "train.py", line 92, in main
>     FLAGS.pipeline_config_path)
>   File "C:\Yolo\DataSets\Data_For_TF_Obecect_detection_API\models-master\research\object_detection\utils\config_util.py", line 94, in get_configs_from_pipeline_file
>     text_format.Merge(proto_str, pipeline_config)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 536, in Merge
>     descriptor_pool=descriptor_pool)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 590, in MergeLines
>     return parser.MergeLines(lines, message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 623, in MergeLines
>     self._ParseOrMerge(lines, message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 638, in _ParseOrMerge
>     self._MergeField(tokenizer, message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
>     merger(tokenizer, message, field)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
>     self._MergeField(tokenizer, sub_message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
>     merger(tokenizer, message, field)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
>     self._MergeField(tokenizer, sub_message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
>     merger(tokenizer, message, field)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
>     self._MergeField(tokenizer, sub_message)
>   File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\google\protobuf\text_format.py", line 730, in _MergeField
>     (message_descriptor.full_name, name))
> **google.protobuf.text_format.ParseError: 32:7 : Message type "object_detection.protos.AnchorGenerator" has no field named "yolo_anchor_generator".**

Can you please guide me what am I missing or doing wrong.
Thanks in advance
M.

**Comment by rky0930** [comment]
Hello @mwindowshz 
I guess this is an error associated with proto.
Did you update all proto files ? Please check your files.

#### Hers is a list of files associated with proto:
- research/object_detection/protos/anchor_generator.proto
- research/object_detection/protos/yolo_anchor_generator.proto
- research/object_detection/protos/losses.proto

**Comment by mwindowshz** [comment]
Hi
What do you mean by update protos
I have used your complete git repository, the protos folder already contains these proto files.

If I understood correctly, as I wrote, the proto files need to be used to generate py files
I used 
```
# From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.
```
each proto has a .py file such as
```
 anchor_generator.proto
anchor_generator_pb2.py
```

all the .py files have _pb2 on the end.

Also I tried, using original Repository and adding all the files as explaind[ in](https://github.com/GustavZ/yolo_for_tf_od_api) 
But it also did not work for me, same error.

So I still did not understand what is missing.
Thanks in advance.

**Comment by rky0930** [comment]
@mwindowshz 
You did right. 
If you cloned my yolo_v2 repo and generate .py files from proto.. It should work. 
Could you send me your source code? So i can reproduce the error and fix the bug.

**Comment by mwindowshz** [comment]
Hi
I am using train.py file in your repository,
I had a problem running the file 

> (TF_API) C:\Users\---\Downloads\Compressed\yolo_v2-master\research\object_detection>python train.py
> Traceback (most recent call last):
>   File "train.py", line 49, in <module>
>     from object_detection import trainer
> **ImportError: cannot import name 'trainer'**

so I changed train.py
```
#from object_detection import trainer
import trainer
```
because trainer is local in object_detection folder. and I am running the train command from object_detection folder.
(other version of the repo have a .\legacy\ folder where the train.py file is placed)

after this, when I run a train with all the flags - training dir, config file path etc, I get the error of  

> "object_detection.protos.AnchorGenerator" has no field named "yolo_anchor_generator".

As you can see, I downloaded the repository, extracted it in a separate folder, run protoc to compile protos, and then try to train.

I also cannot train using any other model such as ssd_inception_v2_coco_2018_01_28

> python train.py --logtostderr --train_dir=D:\train --pipeline_config_path=D:\models\ssd_inception_v2_coco_2018_01_28/pipeline.config

(but this I can run from the original repo)

Error:
```
(TF_API) C:\Users\---\Downloads\Compressed\yolo_v2-master\research\object_detection>python train.py --logtostderr --train_dir=D:\tf-od-api\3classes\Train_Eval_Base_Dir/ssd_inception_v2_coco_2018_01_28/train --pipeline_config_path=D:\tf-od-api\3classes\Base_Modeles_Dir\ssd_inception_v2_coco_2018_01_28/pipeline.config
WARNING:tensorflow:From C:\Users\---\Downloads\Compressed\yolo_v2-master\research\object_detection\trainer.py:210: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
WARNING:tensorflow:From C:\Yolo\DataSets\Data_For_TF_Obecect_detection_API\models-master\research\object_detection\core\preprocessor.py:1205: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 455, in _apply_op_helper
    as_ref=input_arg.is_ref)
  File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\framework\ops.py", line 1159, in internal_convert_n_to_tensor
    ctx=ctx))
  File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\framework\ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\ops\array_ops.py", line 961, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\ops\array_ops.py", line 903, in _autopacking_helper
    elem))
TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int32'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'Preprocessor/stack_1:0' shape=(1, 3) dtype=int32>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 164, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 160, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "C:\Users\---\Downloads\Compressed\yolo_v2-master\research\object_detection\trainer.py", line 228, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "C:\Yolo\DataSets\Data_For_TF_Obecect_detection_API\models-master\research\slim\deployment\model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "C:\Users\---\Downloads\Compressed\yolo_v2-master\research\object_detection\trainer.py", line 155, in _create_losses
    images = tf.concat(images, 0)
  File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1114, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1030, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "C:\ProgramData\Anaconda3\envs\TF_API\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 483, in _apply_op_helper
    raise TypeError("%s that don't all match." % prefix)
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [<NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>] that don't all match.
```

Does this help?
what should I send you.
Thanks.

**Comment by rky0930** [comment]
How about your env setting ?
I think the error down below mean your PYTHONPATH is not set properly.

> Traceback (most recent call last):
>   File "train.py", line 49, in <module>
>     from object_detection import trainer
> **ImportError: cannot import name 'trainer'**

Add Libraries to PYTHONPATH
``` bash
# From tensorflow/models/research/
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
```

**Comment by vkasojhaa** [comment]
@mwindowshz @rky0930 I am facing the same issue when I run `python3 train.py --logtostderr --pipeline_config_path=training/yolo_v2_darknet_19_voc.config --train_dir=training/ .` 
I get this error: 
`google.protobuf.text_format.ParseError: 32:7 : Message type "object_detection.protos.AnchorGenerator" has no field named "yolo_anchor_generator".
`
Did you guys resolve it? I cloned your repo and generated .py files from proto. 

Also I tried, using the original TensorFlow API Repo and adding all the files as explained [here](https://github.com/GustavZ/yolo_for_tf_od_api)  and then generated .py files from proto. 
But it also did not work, got same error.
