### ISSUE TITLE
Not an Issue, but a quick question

### ISSUE THREAD

**Issue by ltorlay** [rky0930/yolo_v2#7]
Is it possible to change the network structure here without any adverse effects? I was curious if I can make it a structure similar to that of tiny-YoloV2.

Please let me know! 

Thanks

**Comment by rky0930** [comment]
Yes, you can create your version of yolo based on Object Detection API. 
For me, I made my yolo v2 based on SSD Structure by adding & modifying some code. 
I'm not sure about adverse effect, At the first time when i wrote this code, the result was not so good, after many debugging / training / testing, I got good result.
But I really like the approach, after made once, There are many benefit. 
Good luck to you !

**Comment by ltorlay** [comment]
Thank you for your help!

**Comment by ltorlay** [comment]
I actually wanted to ask another question regarding how you ultimately implemented the network with training. I ran the train.py script on my slightly modified yolo_v2_darknet_tiny.config file and found that I had errors associated with an yolo_meta_arch.py script that I did not include in my model_builder.py. I know this was awhile ago, but I was wondering if you could recall anything else outside of the "Added or Updated file list" which I should tack on to what I have like that meta architecture?   

Thanks!

**Comment by rky0930** [comment]
@ltorlay I think that's all files i added or modified. 
If you share your code to me. I will check.

**Comment by ltorlay** [comment]
Sorry for the delayed response, but I ended up figuring it out. It was just
a typo I mistakenly made while editing a file.

Thanks!
